### PR TITLE
Arctic Vessels & Sea Ice

### PR DESCRIPTION
**Pull request by Joshdpaul**
This notebook uses a locally downloaded arctic vessel dataset and fetches spatially corresponding sea ice concentration data via the SNAP Data API. The fused datasets are then binned by latitude and plotted, with some cartography thrown in as well. There is a fair amount of dataframe wrangling, matplotlibbing, and generally a lot of code - so I'd throw this in the more "advanced" bin of notebooks even though the plot formatting ends up rather simple-looking.

Closes ua-snap/ardac#153

**I did not update the environment.yml file! so you will need to install the packages listed in the setup cell in order to run the notebook.**

To test, simply install the packages and run the notebook. 

Things I'd like input on:

- you will see that I request sea ice data for >5000 lat/lons, and its sort of messy how I split the requests into 4 groups to avoid overloading the server. In truth, this use-case probably calls for downloading a local copy of the sea ice datacube and querying it directly, but I wanted to show the use of the API here. Any suggestions for cleaning this up while still using the API?
- I created a series of `asyncio` functions to fetch the sea ice data. Honestly this took me a while to figure out and I don't completely understand the `async` & `await` relationship: do these functions look to be implemented properly? I mean they do work (and work quickly) but maybe this can be accomplished with less code/cleaner code?

### CODE REVIEW

**Review by kyleredilla — CHANGES_REQUESTED** [review]
This is great so far! I (again) appreciate the background text and the analysis idea here, and the plotting is great. I think that adding more and more variety of plotting / cartography is only good at this point. 

I didn't get all the way through the PR though, as I cancelled execution of the API request cell after the requests were running for about 13 minutes. I think we should do some reconsidering here.

I agree that this particular analysis is not really a great use case for the API, and I would recommend performing that analysis with the full dataset, as it is fairly light (38MB on [portal](http://data.snap.uaf.edu/data/Base/Other/Historical_Sea_Ice_Atlas/)) and downloads in seconds. Alternatively, you could construct a WCS request that talks to Rasdaman directly and pulls only the data for the spatial and temporal extent of the shipping dataset, which you could construct an xarray dataset from (as is done in one of the recent notebooks) and then run a similar extraction using that subdataset to get the concentrations. 

The current pattern of API requests for all possible hexagon centroids just seems like something we don't want to promote. I think it's generally an indication that you should look for another route to the data if you are having to tailor your request structure to avoid overloading a server. The analysis is essentially joining two datasets, but going through the API seems like a relatively inefficient route compared to just downloading the dataset. 

If you want to use the API, I guess my first thought is to demonstrate using the API for a couple of requests, e.g. a handful of hex cells, and using the same method you currently have (without the request "chunking" ). Like, "say we want to get the sea ice concentrations for this small group of cells...". Then you could escalate and be like "OK, what if we want to do this for the entire dataset?". You could even use that as an opportunity to demonstrate that you are then stepping from "API use case" to "data portal use case", if that makes sense.

**Comment by Joshdpaul** [comment]
@kyleredilla thanks for those comments! I revised the analysis to make only 10% of the requests, by limiting the spatial extent to just the Bering Sea region. The request will not overload the server and goes quickly now for me - how long does it take for you?. 

The concatenation of the hexagon datasets still takes ~5min, and the "small multiples" plots at the end take a long time in this notebook (~10 min for both). Those "small multiples" maps may not be necessary here, but I figured I would include them because I thought they were interesting. I might zoom them into a particular port (Nome?) in order to speed up the plotting.

I should note that some of the context for why I decided to not use the raster dataset or WCS request is simply to add variety in the notebooks. Given your work with the ERA5 and Rasdman access notebooks, focusing on vector data seemed like a good way to add some diversity in these analyses. But, if you find that it takes forever, maybe I add in the raster processing for the second half of the notebook as you suggested.

**Review by kyleredilla — CHANGES_REQUESTED** [review]
I appreciate wanting to diversify with vector data 👍 and by limiting the requests to a specific region that definitely improves this example's utility as an API use case! Good re-work.

(Note - I can't open the file in GH to make specific change requests / comments, so I will just leave everything in this comment.)

--------

It still seems kinda borderline as an API use case (vs raw dataset), as it still took 10 minutes to get the data back from the API, so I would recommend adding a note about that (e.g. "this could take a while"). I did actually run into an issue with the API calls, with a handful of the requests failing even though they are valid requests: 

image

I assume this is probably due to a similar / the same issue you were having with the original request load, unless you can tell otherwise by that screenshot. 

I was able to continue the notebook by just retrying the ones that failed with:
```
retry_url_dict = {
    hexid: hexid_url_dict[hexid] for hexid in hexid_url_dict if result[hexid] == None
}
await main(hexid_url_dict, result)
```

I'll leave it up to you if you want to make any changes to make that more resilient. 

Another note on that - currently, the failure mode logging (the `print` statements) just lets you know that some URLs failed, which is a little confusing, because it is expected that none of them fail. That feels like that is more for debugging the API access, and that we might want to drop it, or explain it's presence. Might help to include a note somewhere explaining that failed requests don't necessarily mean invalid requests, and how to retry (if you go that route). You could also limit the requests even more, or implement some automatic retry logic.  Unfortunately it doesn't seem like there is built-in ability for aiohttp retries (although there is a [standalone library](https://pypi.org/project/aiohttp-retry/))

---

I dropped `ticklabels = twin_b.get_xticklabels()` from the "Plotting open water & vessel operating days by category" cell, which seems to have silenced the `UserWarning`, if you would like to verify that. 

---

The monthly averages plot is not appearing the same to me. I would guess this could be an issue with my need to retry some of the endpoints? Although it is strange, I have compared my tables with yours and they match. I also re-ran the whole API request. Here is what my maps look like, there is a distinct lack of sea ice in multiple months compared to what I am seeing in the GH preview of your version:

image

One thing I noticed when digging in is that the `merge` operation to get the `map_df` object appears to be including duplicate rows because there are duplicates in the `bering_3338[["hexID", "geometry"]]` dataframe. Dropping them seems to fix that aspect, and it seemed to affect plotting. Maybe the duplicates are actually plotting on top of each other, or something? That kinda seems like the case, which is supported by the fact that the hexagons are not really visible in some of the plots, compared with the small multiples plot, where the outlines are visible.

```
map_df = map_df.merge(bering_3338[["hexID", "geometry"]].drop_duplicates(), on="hexID")
```

So maybe try that out? Or do what you have done to accomplish this (`.first()` method) in the "small multiples" cell, as I just noticed:

```
map_df = map_df.merge(
    bering_3338.groupby("hexID", as_index=False)["geometry"].first(),
    how="left",
    on="hexID",
)
```

---

In the small multiples cell, here is a suggestion to cut down on the code:

```
months = [m.zfill(2) for m in np.arange(4, 13).astype(str)]
map_df = (
    bering_3338[
        bering_3338["month"].isin(
            months
        )
    ]
    .groupby(["hexID", "year", "month"], observed=True, as_index=False)[
        "sea_ice_concentration"
    ]
    .mean()
)
map_df = map_df.merge(
    bering_3338.groupby("hexID", as_index=False)["geometry"].first(),
    how="left",
    on="hexID",
)

map_gdf = gpd.GeoDataFrame(map_df, geometry="geometry", crs=3338)

# in this way, axes is a 2D array
fig, axes = plt.subplots(6, 9, figsize=(14, 7))

vmin = 0
vmax = 100
f = 6

for year, month, ax in zip(
    np.repeat(np.arange(2015, 2021).astype(str), len(months)),
    np.tile(months, 6),
    # this unwraps the 2D array of axes into a flat (1D) array
    axes.flatten(),
):
    df = map_gdf[(map_gdf["month"] == month) & (map_gdf["year"] == year)]
    df.plot(
        "sea_ice_concentration",
        cmap="BuPu",
        ax=ax,
        # alpha=0.7,
        zorder=0,
        vmin=vmin,
        vmax=vmax,
    )

    continents_3338.plot(ax=ax, linewidth=0.7, fc="lightgray", ec="black", zorder=1)

    transformer = Transformer.from_crs("EPSG:4326", "EPSG:3338", always_xy=True)
    lats = [62, 63, 64, 65, 66, 67, 68]

    for lat in lats:
        lon1 = np.linspace(160, 180)
        lon2 = np.linspace(-180, -135)
        lat_ = np.linspace(lat, lat)
        x1, y1 = transformer.transform(xx=lon1, yy=lat_)
        x2, y2 = transformer.transform(xx=lon2, yy=lat_)
        ax.plot(x1, y1, linewidth=0.4, color="firebrick", linestyle="--")
        ax.plot(x2, y2, linewidth=0.4, color="firebrick", linestyle="--")

    ax.set_xlim(-1000000, -190000)
    ax.set_ylim(1500000, 2000000)

    ax.set_xticklabels([])
    ax.set_xticks([])
    ax.set_yticklabels([])
    ax.set_yticks([])

    ax.set_title(year + "/" + month, fontsize=f)

plt.tight_layout
plt.show()
```

Maybe consider dropping the `alpha=0.7` in either or both plots as well? Unless you just prefer how it looks - it just feels kind of muted to me. But maybe I am missing why the transparency helps! 

---

Finally, I would suggest dropping commented out code that isn't used, or doesn't have an alternative use explained to the user (e.g. `# uncomment this block to do x` is OK)

---

Nice work! This one is so close!

**Comment by Joshdpaul** [comment]
@kyleredilla Thanks for the thorough review, and the great suggestions. I think I covered all your comments in these last commits, which include an optional "retry" block of code for the http requests, more explanation about possible reasons for request errors, and a general shrinking of the analysis area to speed up requests and plotting.

Thanks for providing a shorter version of the small multiples code block! I tried doing something similar but failed because I did not know the syntax for zipping the repeating months/years, so I originally did it the long way. Your code worked great, and I improved the formatting of both plots a little bit too. 

Seeing as you will be out of office for a while, I am just going to merge this into `main` and get it over with! I appreciate your close attention on this one!

**Pull request merged**
